[workspace]
name = "bioconda-docs"
version = "0.1.0"
description = "Bioconda documentation build environment"
authors = ["The Bioconda Team"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.10"
sphinx = ">=7.0"
sphinx-autodoc-typehints = "*"
celery = "*"
bioconda-utils = "*"
pydata-sphinx-theme = "*"
make = "*"
sphinx-autobuild = "*"
sphinx-copybutton = "*"

[tasks]
dev = { cmd = "sphinx-autobuild source build/html", env = { BIOCONDA_FILTER_RECIPES = "10" } }
